// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateMovie(ctx context.Context, arg CreateMovieParams) (CreateMovieRow, error)
}

var _ Querier = (*Queries)(nil)
